var visdataset=null;var dopdataset=null;var timelinedataset=null;var barchart=null;var barchart1=null;var rangechart=null;var countryindex=0;var exportvalue="";var tablehtml="";var sel=null;function dataof(country){countryindex=0;var cs=$('#visualizationiframe')[0].contentWindow.countries_stations;for(var i=0;i<cs.length;i++){var cslabel=cs[i].label;if(cslabel==country){return i;}}
return countryindex;}
function removestamp(){$('.anychart-credits').css('height',"0px");}
function initcontainer1(doparray){if(barchart1==null){barchart1=anychart.line();barchart1.animation(true);barchart1.crosshair(true);barchart1.container('container1');barchart1.padding([10,40,5,20]);var title=barchart1.title();title.enabled(true);title.useHtml(true);title.text('<b>DOP by Time</b><br>'+'<h style=\"text-align:right; font-size:70%;\">'+"System : "+systemname.split(" [")[0]+
(appendsystemname==""?"":(" + "+appendsystemname))+"&nbsp;&nbsp;&nbsp;&nbsp;</h>"+'<h style=\"text-align:right; font-size:70%;\">'+($(".performance-country").val().indexOf("CustomPoint")!=-1?("Lat:"+sel.lat+" Lon:"+sel.lon):("Station : "+$(".performance-country").val()))+"&nbsp;&nbsp;&nbsp;&nbsp;Time : "+$("#performance-date").val()+"</h>");barchart1.xAxis().title('Time [/hour]');barchart1.yAxis().title('DOP Value');var yScale=barchart1.yScale();yScale.minimum(0);yScale.ticks().interval(1);yScale.minorTicks().interval(1);var yLabels=barchart1.yAxis().labels();yLabels.width(30);var xLabels=barchart1.xAxis().labels();xLabels.width(30);barchart1.yAxis().staggerMode(false);barchart1.xAxis().labels().textFormatter(function(){var value=this.value;value=value.toLocaleString().split(" ")[1];if(value){value=value.substr(0,2);if(value<10)value=value.substr(1,1);}
return value});barchart1.yAxis().staggerMode(false);barchart1.grid(true);barchart1.minorGrid(true);barchart1.legend().enabled(true).fontSize(13).padding([0,0,20,0]);barchart1.draw();}
else{barchart1.removeAllSeries();barchart1.title().useHtml(true);barchart1.title().text('<b>DOP by Time</b><br>'+'<h style=\"text-align:right; font-size:70%;\">'+"System : "+systemname.split(" [")[0]+
(appendsystemname==""?"":(" + "+appendsystemname))+"&nbsp;&nbsp;&nbsp;&nbsp;</h>"+'<h style=\"text-align:right; font-size:70%;\">'+($(".performance-country").val().indexOf("CustomPoint")!=-1?("Lat:"+sel.lat+" Lon:"+sel.lon):("Station : "+$(".performance-country").val()))+"&nbsp;&nbsp;&nbsp;&nbsp;Time : "+$("#performance-date").val()+"</h>");}
var setupSeries=function(series,name){var seriesLabels=series.labels();series.hoverLabels().enabled(false);seriesLabels.enabled(true);seriesLabels.position('right');seriesLabels.textFormatter(function(){return'$'+this.value.toLocaleString();});series.name(name);seriesLabels.anchor('left');series.tooltip().titleFormatter(function(){return this.x;});series.tooltip().textFormatter(function(){return name+" : "+this.value;});series.tooltip().position('right').anchor('left').offsetX(5).offsetY(0);};dopdataset=anychart.data.set(doparray);var seriesData_1=dopdataset.mapAs({x:[0],value:[1]});var seriesData_2=dopdataset.mapAs({x:[0],value:[2]});var seriesData_3=dopdataset.mapAs({x:[0],value:[3]});var seriesData_4=dopdataset.mapAs({x:[0],value:[4]});var seriesData_5=dopdataset.mapAs({x:[0],value:[5]});barseries=barchart1.line(seriesData_1).name('HDOP').hoverMarkers().enabled(true).type('circle').size(4);;barseries=barchart1.line(seriesData_2).name('VDOP').hoverMarkers().enabled(true).type('circle').size(4);;barseries=barchart1.line(seriesData_3).name('PDOP').hoverMarkers().enabled(true).type('circle').size(4);;barseries=barchart1.line(seriesData_4).name('TDOP').hoverMarkers().enabled(true).type('circle').size(4);;barseries=barchart1.line(seriesData_5).name('GDOP').hoverMarkers().enabled(true).type('circle').size(4);;}
function initcontainer2(satarray){if(barchart==null){visdataset=anychart.data.set(satarray);barchart=anychart.column();barchart.animation(true);barchart.container('container2');barchart.padding([10,40,5,20]);var title=barchart.title();title.enabled(true);title.useHtml(true);title.text('<b>Visibility by Time</b><br>'+'<h style=\"text-align:right; font-size:70%;\">'+"System : "+systemname.split(" [")[0]+
(appendsystemname==""?"":(" + "+appendsystemname))+"&nbsp;&nbsp;&nbsp;&nbsp;</h>"+'<h style=\"text-align:right; font-size:70%;\">'+($(".performance-country").val().indexOf("CustomPoint")!=-1?("Lat:"+sel.lat+" Lon:"+sel.lon):("Station : "+$(".performance-country").val()))+"&nbsp;&nbsp;&nbsp;&nbsp;Time : "+$("#performance-date").val()+"</h>");barchart.xAxis().title('Time [/hour]');barchart.yAxis().title('Satellite Count [/satellites]');var yScale=barchart.yScale();yScale.minimum(0);yScale.ticks().interval(1);yScale.minorTicks().interval(1);var yLabels=barchart.yAxis().labels();yLabels.width(30);var xLabels=barchart.xAxis().labels();xLabels.width(30);barchart.yAxis().staggerMode(false);barchart.xAxis().labels().textFormatter(function(){var value=this.value;value=value.toLocaleString().split(" ")[1];if(value){value=value.substr(0,2);if(value<10)value=value.substr(1,1);}
return value});barchart.yAxis().staggerMode(false);barchart.grid(true);barchart.minorGrid(true);barchart.interactivity().hoverMode('byX');barchart.tooltip().positionMode('point');barchart.draw();}else{barchart.removeAllSeries();while(visdataset.getRowsCount()!=0){visdataset.remove(0);}
for(var i=satarray.length;i>0;i--){visdataset.insert(satarray[i]);}
barchart.title().useHtml(true);barchart.title().text('<b>Visibility by Time</b><br>'+'<h style=\"text-align:right; font-size:70%;\">'+"System : "+systemname.split(" [")[0]+
(appendsystemname==""?"":(" + "+appendsystemname))+"&nbsp;&nbsp;&nbsp;&nbsp;</h>"+'<h style=\"text-align:right; font-size:70%;\">'+($(".performance-country").val().indexOf("CustomPoint")!=-1?("Lat:"+sel.lat+" Lon:"+sel.lon):("Station : "+$(".performance-country").val()))+"&nbsp;&nbsp;&nbsp;&nbsp;Time : "+$("#performance-date").val()+"</h>");}
barseries=barchart.column(visdataset);barseries.tooltip().textFormatter(function(){return"Visibility of "+this.value+" Satellites";});}
function initcontainer3(satarrays){if(rangechart!=null){rangechart.removeAllSeries();rangechart.title().useHtml(true);rangechart.title().text('<b>Coverage by Time</b><br>'+'<h style=\"text-align:right; font-size:70%;\">'+"System : "+systemname.split(" [")[0]+
(appendsystemname==""?"":(" + "+appendsystemname))+"&nbsp;&nbsp;&nbsp;&nbsp;</h>"+'<h style=\"text-align:right; font-size:70%;\">'+($(".performance-country").val().indexOf("CustomPoint")!=-1?("Lat:"+sel.lat+" Lon:"+sel.lon):("Station : "+$(".performance-country").val()))+"&nbsp;&nbsp;&nbsp;&nbsp;Time : "+$("#performance-date").val()+"</h>");}
else{rangechart=anychart.bar();rangechart.container('container3');rangechart.animation(true);var title=rangechart.title();title.enabled(true);title.useHtml(true);title.text('<b>Availability by Time</b><br>'+'<h style=\"text-align:right; font-size:70%;\">'+"System : "+systemname.split(" [")[0]+
(appendsystemname==""?"":(" + "+appendsystemname))+"&nbsp;&nbsp;&nbsp;&nbsp;</h>"+'<h style=\"text-align:right; font-size:70%;\">'+($(".performance-country").val().indexOf("CustomPoint")!=-1?("Lat:"+sel.lat+" Lon:"+sel.lon):("Station : "+$(".performance-country").val()))+"&nbsp;&nbsp;&nbsp;&nbsp;Time : "+$("#performance-date").val()+"</h>");rangechart.xAxis().title('Satellite Name');rangechart.yAxis().title('Time [/hour]');var yScale=rangechart.yScale();yScale.minimum(0);yScale.maximum(24);yScale.ticks().interval(1);yScale.minorTicks().interval(1);var yLabels=rangechart.yAxis().labels();yLabels.width(30);yLabels.height(20);rangechart.yAxis().staggerMode(false);var xLabels=rangechart.xAxis().labels();xLabels.width(70);xLabels.height(20);rangechart.xAxis().overlapMode("allowOverlap");rangechart.xAxis().staggerMode(true);rangechart.xAxis().staggerLines(1);rangechart.xAxis().labels().textFormatter(function(){var value=this.value;if(value.toLocaleString().indexOf(" ")<7){value=value.toLocaleString().substr(value.toLocaleString().indexOf(" "),value.toLocaleString().length);}
else{value=value.toLocaleString();}
return value});rangechart.grid(true);rangechart.minorGrid(true);rangechart.draw();}
for(var i=0;i<satarrays.length;i++){var data_lon=anychart.data.set(satarrays[i]);var series_lon=rangechart.rangeBar(data_lon);var tooltip=rangechart.getSeries(i).tooltip();tooltip.titleFormatter("{%x}");tooltip.textFormatter("Start: {%high}\nEnd: {%low}");}}
var tablehashmap;function initcontainer4(hashmap,timestr){tablehashmap=hashmap;tablehtml="<select id='tableoption' onchange='updatetable(this.value);' style='width:50%;float:right;border:none;'>";for(var i=0;i<hashmap.keySet().length;i++){tablehtml+="<option "+
(i==hashmap.keySet().length-1?"selected='selected'":"")+"'>"+hashmap.keySet()[i]+"</option>";}
tablehtml+="</select>";tablehtml+="<table class='visibilitytable' style='color:#000;'>";tablehtml+=updatetable(timestr,true)+"</div>";tablehtml+="</table>";}
var tablecontentstr="";function updatetable(selection,ret){var timestr=selection;tablecontentstr="";var tablecontent="";tablecontent+="<tr><td colspan='6'>TIME: "+timestr+"<br/>";tablecontentstr+="TIME: "+timestr+"\n";tablecontent+="JulianDate: "+$('#visualizationiframe')[0].contentWindow.currentJulianDate.getJulianDate()+"<br/>";tablecontentstr+="JulianDate: "+$('#visualizationiframe')[0].contentWindow.currentJulianDate.getJulianDate()+"\n";tablecontent+="Location: "+sel.label+"<br/>";tablecontentstr+="Location: "+sel.label+"\n";tablecontent+="Latitude: "+sel.lat+"<br/>";tablecontentstr+="Latitude: "+sel.lat+"\n";tablecontent+="Longitude: "+sel.lon+"</td></tr>";tablecontentstr+="Longitude: "+sel.lon+"\n";tablecontent+="<tr><td>No.</td><td>Satellite Name</td><td>Latitude</td><td>Longitude</td><td>Elevation</td><td>Azimuth</td></tr>";tablecontentstr+="--------------------------------------------------------------------------------------------------------------\n";tablecontentstr+="|  No.  |---|      Satellite Name      |---|  Latitude  |---|  Longitude  |---|  Elevation  |---|   Azimuth  |\n";tablecontentstr+="--------------------------------------------------------------------------------------------------------------\n";var value=tablehashmap.get(timestr);for(var j=0;j<value.length;j++){var pos=$('#visualizationiframe')[0].contentWindow.toLATLONTEXT($('#visualizationiframe')[0].contentWindow.toNormalLATLON(parseFloat(value[j].Position.x),parseFloat(value[j].Position.y),parseFloat(value[j].Position.z))).replace("(","").replace(")","");tablecontent+="<tr><td>"+(j+1)+"</td><td>"+value[j].Name+"</td><td>"+parseFloat(pos.split(",")[0]).toFixed(2)+"</td><td>"+parseFloat(pos.split(",")[1]).toFixed(2)+"</td><td>"+(value[j].Elevation).toFixed(2)+"</td><td>"+(value[j].Azimuth).toFixed(2)+"</td></tr>";var space="";while((value[j].Name.trim().length+space.length)<17){space+=" ";}
tablecontentstr+="|  "+((j+1)<10?" ":"")+(j+1)+"   |---|      "+value[j].Name.trim()+space+"   |---|  ";var lat=parseFloat(pos.split(",")[0]).toFixed(2);space="";while((lat.length+space.length)<6){space+=" ";}
tablecontentstr+=lat+space+"    |---|  ";var lon=parseFloat(pos.split(",")[1]).toFixed(2);space="";while((lon.length+space.length)<7){space+=" ";}
tablecontentstr+=lon+space+"    |---|  ";var el=(value[j].Elevation).toFixed(2);space="";while((el.length+space.length)<7){space+=" ";}
tablecontentstr+=el+space+"    |---|  ";var az=(value[j].Azimuth).toFixed(2);space="";while((az.length+space.length)<6){space+=" ";}
tablecontentstr+=az+space+"    |\n";}
$('.visibilitytable').html(tablecontent);tablecontentstr+="-------------------------------------------------------------------------------------------------------------\n";if(ret)
return tablecontent;}
function resetChartDataWW(){console.log("Recalculate Performance with worker");resetexportvalue();countryindex=dataof($("select.performance-country option:selected").val().split("_")[1]);sel=$('#visualizationiframe')[0].contentWindow.countries_stations[countryindex];showloading(true);$('#visualizationiframe')[0].contentWindow.SatelliteWorkers[0].postMessage({funct:'calculatechart',param:{lat:parseFloat(sel.lat),lon:parseFloat(sel.lon),time:$("#performance-date").val(),range:$("#performance-time").val()}});}
function chartcompleteWW(satarray,doparray,dopkeys,satarrays,exportvalue){addexportvalue(satarray);addexportvalue(exportvalue);initcontainer2(satarray);addexportvalue(doparray);initcontainer1(doparray);initcontainer3(satarrays);showloading(true);$('#visualizationiframe')[0].contentWindow.SatelliteWorkers[0].postMessage({funct:'calculatecompletechart',param:{lat:parseFloat(sel.lat),lon:parseFloat(sel.lon),currtime:$('#visualizationiframe')[0].contentWindow.currentJulianDate.getDateTimeStr()}});console.log("current time",$('#visualizationiframe')[0].contentWindow.currentJulianDate.getDateTimeStr());}
function chartfinishWW(satarray){var visiblehashmap=new hashmap();for(var i=0;i<satarray.length;i++){visiblehashmap.put(satarray[i][0],satarray[i][1]);}
initcontainer4(visiblehashmap,visiblehashmap.keySet()[visiblehashmap.keySet().length-1]);$('#container1').height($('#img-container').height());$('#container2').height($('#img-container').height());$('#container3').height($('#img-container').height());if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/)||navigator.userAgent.match(/Windows Phone/i)||navigator.userAgent.match(/ZuneWP7/i)){}
else{var sgp4total=$('#visualizationiframe')[0].contentWindow.BigEarth.SGP4Array.length;if(sgp4total*25>$('#img-list').height())
$('#container3').height((sgp4total*25)+'px');}
visiblehashmap=null;endexportvalue();removestamp();$('#performance-contain4').click(function(e){$('#container4').html(tablehtml);});$('#performance-contain5').click(function(e){$('#container5').html($('#tutorial').html());$('#container5').css("color","#000")});$('#performance-contain4').click();setTimeout(function(){$('#performance-contain5').click();},100);setTimeout(function(){$('#performance-contain3').click();},200);}
function resetChartData(){console.log("Recalculate Performance");resetexportvalue();countryindex=dataof($("select.performance-country option:selected").val().split("_")[1]);sel=$('#visualizationiframe')[0].contentWindow.countries_stations[countryindex];$('#visualizationiframe')[0].contentWindow.BigEarth.calculateallVisible(parseFloat(sel.lat),parseFloat(sel.lon),$("#performance-date").val(),$("#performance-time").val());var hashmap=$('#visualizationiframe')[0].contentWindow.visiblehashmap;var satarray=[];for(var i=0;i<hashmap.keySet().length-1;i++){var key=hashmap.keySet()[i];var value=hashmap.get(key);if(value)
satarray.push([key,value.length]);}
addexportvalue(satarray);initcontainer2(satarray);var dopmap=$('#visualizationiframe')[0].contentWindow.dophashmap;if(dopmap.keySet().length>0){var dopkeys=dopmap.get(dopmap.keySet()[0]).keySet();var doparray=[];for(var j=0;j<dopmap.keySet().length;j++){var darray=[];var key=dopmap.keySet()[j];darray.push(key);for(var i=0;i<dopkeys.length;i++){var value=dopmap.get(key).get(dopkeys[i]);if(value)
darray.push(value);}
doparray.push(darray);}
addexportvalue(doparray);}
initcontainer1(doparray);var roothmap=calculatecoveragetimerange(hashmap,$("#performance-time").val());var satname="";var high="";var low="";var satarrays=[];for(var i=0;i<roothmap.length;i++){satarray=[];for(var j=0;j<roothmap[0].keySet().length;j++){var name=roothmap[0].keySet()[j];if(roothmap[i].keySet().indexOf(name)==-1){if(i!=0&&name.indexOf("_end")!=-1){}
continue;}
if(name.indexOf("_start")!=-1){satname=name.replace("_start","");high=roothmap[i].get(name);}
else if(name.indexOf("_end")!=-1){low=roothmap[i].get(name);satarray.push({low:low,high:high,x:satname});addexportvalue(satname+" "+"Begin: "+high+" End: "+low);}}
satarray.sort(function(a,b){var nameA=a.x.toLowerCase(),nameB=b.x.toLowerCase()
if(nameA<nameB)
return-1
if(nameA>nameB)
return 1
return 0})
satarrays.push(satarray);}
initcontainer3(satarrays);$('#visualizationiframe')[0].contentWindow.BigEarth.calculateperformanceVisiblility(parseFloat(sel.lat),parseFloat(sel.lon),$('#visualizationiframe')[0].contentWindow.currentJulianDate.getDateTimeStr(),true);var hs=$('#visualizationiframe')[0].contentWindow.visiblehashmap;initcontainer4(hashmap,hs.keySet()[hs.keySet().length-1]);$('#container1').height($('#img-container').height());$('#container2').height($('#img-container').height());$('#container3').height($('#img-container').height());if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/)||navigator.userAgent.match(/Windows Phone/i)||navigator.userAgent.match(/ZuneWP7/i)){}
else{var sgp4total=$('#visualizationiframe')[0].contentWindow.BigEarth.SGP4Array.length;if(sgp4total*25>$('#img-list').height())
$('#container3').height((sgp4total*25)+'px');}
hashmap=null;endexportvalue();removestamp();$('#performance-contain4').click(function(e){$('#container4').html(tablehtml);});setTimeout(function(){$('#performance-contain4').click();},300);$('#performance-contain5').click(function(e){$('#container5').html($('#tutorial').html());});setTimeout(function(){$('#performance-contain5').click();},300);setTimeout(function(){$('#performance-contain1').click();},500);setTimeout(function(){$('#performance-contain2').click();},200);setTimeout(function(){$('#performance-contain3').click();},300);}
function calculatecoveragetimerange(map,range){var multihashmaproot=[];var hashmaptemp=new hashmap();var i=0;for(var r=0;r<=24*60*60;r=parseInt(r)+parseInt(range)){var currtime=map.keySet()[i++];for(var j=0;j<map.get(currtime).length;j++){var name=map.get(currtime)[j].Name;addexportvalue(currtime+" "+name);if(hashmaptemp.keySet().indexOf(name+"_start")==-1){hashmaptemp.put(name+"_start",r/3600);hashmaptemp.put(name+"_end",r/3600);}
else{hashmaptemp.put(name+"_end",r/3600);}}
for(var j=0;j<hashmaptemp.keySet().length;j++){var name=hashmaptemp.keySet()[j];if(name.indexOf("_end")!=-1){if(hashmaptemp.get(name)!=r/3600||r>=24*60*60){var satname=name.replace("_end","");if(multihashmaproot.length==0){}
for(var k=0;k<=multihashmaproot.length;k++){if(multihashmaproot[k]);else
multihashmaproot.push(new hashmap());if(multihashmaproot[k].keySet().indexOf(satname+"_start")==-1){multihashmaproot[k].put(satname+"_start",hashmaptemp.get(satname+"_start"));multihashmaproot[k].put(satname+"_end",hashmaptemp.get(satname+"_end"));hashmaptemp.remove(satname+"_end");break;}}}}
else{hashmaptemp.put(satname+"_start",hashmaptemp.get(satname+"_start"));}}
for(var j=0;j<hashmaptemp.keySet().length;j++){if(hashmaptemp.keySet()[j].indexOf("_start")!=-1){var satname=hashmaptemp.keySet()[j].replace("_start","");var exist=false;for(var k=0;k<map.get(currtime).length;k++){if(map.get(currtime)[k].Name==satname){exist=true;break;}}
if(exist==false){hashmaptemp.remove(satname+"_start");hashmaptemp.remove(satname+"_end");}}}}
hashmaptemp=null;return multihashmaproot;}
var selectedcontainerid="3";function exportdata(e){if(selectedcontainerid=="4"){download("SATINFO_Performance-evaluation.txt",tablecontentstr);return;}
else if(selectedcontainerid=="5"){alert("Please select chart to export!");return;}
switch(e){case'0':download("SATINFO_Performance-evaluation.txt",exportvalue);break;case'1':downloadExportSVGto("container"+selectedcontainerid,"svg");break;case'2':downloadExportSVGto("container"+selectedcontainerid,"png");break;case'3':downloadExportSVGto("container"+selectedcontainerid,"jpg");break;default:;}
$('#performance-export').val("");}
function download(filename,text){var pom=document.createElement('a');pom.setAttribute('href','data:text/plain;charset=utf-8,'+encodeURIComponent(text));pom.setAttribute('download',filename);if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)){var myBaseString=('data:text/plain;charset=utf-8,'+encodeURIComponent(text));var block=myBaseString.split(";");var dataType=block[0].split(":")[1];var realData=block[1].split(",")[1];var folderpath=cordova.file.externalRootDirectory;var filename="SATINFO_Performance-evaluation.txt";console.log(folderpath,filename,realData,dataType);savebase64AsImageFile(folderpath,filename,text,dataType);}else{if(document.createEvent){var event=document.createEvent('MouseEvents');event.initEvent('click',true,true);pom.dispatchEvent(event);}
else{pom.click();}
alert("Successfully saved!");}}
function downloadExportSVGto(containerid,type){var containername="";switch(containerid){case'container1':containername="SATinfo_DOPbyTime";break;case'container2':containername="SATinfo_VISIBILITYbyTime";break;case'container3':containername="SATinfo_AVAILABILITYbyTime";break;}
var wrapper=document.getElementById(containerid);var svg=wrapper.querySelector("svg");if(typeof window.XMLSerializer!="undefined"){var svgData=(new XMLSerializer()).serializeToString(svg);}else if(typeof svg.xml!="undefined"){var svgData=svg.xml;}
if(type=="png"||type=="jpg"){var canvas=document.createElement("canvas");var svgSize=svg.getBoundingClientRect();canvas.width=svgSize.width;canvas.height=svgSize.height;var context=canvas.getContext("2d");var img=document.createElement("img");img.setAttribute("src","data:image/svg+xml;base64,"+btoa(unescape(encodeURIComponent(svgData))));img.onload=function(){context.drawImage(img,0,0);var logoimage=new Image();logoimage.onload=function(){context.drawImage(this,context.canvas.width-110,5);var imgsrc=canvas.toDataURL("image/"+type);if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)){var myBaseString=imgsrc;var block=myBaseString.split(";");var dataType=block[0].split(":")[1];var realData=block[1].split(",")[1];var folderpath=cordova.file.externalRootDirectory;var filename="SATinfo"+"."+type;console.log(folderpath,filename,realData,dataType);savebase64AsImageFile(folderpath,filename,realData,dataType);}else{var a=document.createElement("a");a.download=containername+"."+type;a.href=imgsrc;a.click();alert("Successfully saved!");}};logoimage.src='images/logo_new_black.png';};}
else if(type=="svg"){var svgdataurl="data:image/svg+xml;base64,"+btoa(unescape(encodeURIComponent(svgData)))
if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)){var myBaseString=svgdataurl;var block=myBaseString.split(";");var dataType=block[0].split(":")[1];var realData=block[1].split(",")[1];var folderpath=cordova.file.externalRootDirectory;var filename="SATinfo.svg";console.log(folderpath,filename,realData,dataType);savebase64AsImageFile(folderpath,filename,realData,dataType);}else{var a=document.createElement("a");a.download=containername+".svg";a.href=svgdataurl;a.click();alert("Successfully saved!");}}}
function resetexportvalue(){exportvalue="#####################################\n";exportvalue+="##SATINFO2.0 PERFORMANCE EVALUATION##\n";exportvalue+="#####################################\n";exportvalue+="Observation System: "+systemname+"\n";exportvalue+="Observation Point: "+$("select.performance-country option:selected").val()+"\n";exportvalue+="Observation Time: "+$("#performance-date").val()+"\n";}
function addexportvalue(value){exportvalue+="\n";exportvalue+=value.toString().split("UTC,").join("UTC : ").split(",").join("\n").split("<br/>").join("\n");exportvalue+="\n";}
function endexportvalue(){exportvalue+="#####################################";$("#performance-export a").attr("href",'data:text/plain;charset=UTF-8,'+encodeURIComponent(exportvalue));}