var data="";var systemname="";var appendsystemname="";var datamode="[null]";var mode=undefined;function DisplayREALTLE(a,b,c){if($('.customfunction').css("display")=="none"&&$('.visualization-info').css("display")=="block")
$('.customfunction').css("display","inline-block");if(c){if(c.innerHTML=="-")c=true;else c=false;}
if(systemname==""){c=undefined;}
if(c==true){if(appendsystemname.indexOf(a)!=-1||systemname.toLowerCase().indexOf(a)!=-1)return;}
if(data!=null){$('#visualizationiframe')[0].contentWindow.BigEarth.removeAll();$('#visualizationiframe')[0].contentWindow.SmallEarth.removeAll();}
if(a=='custom'){$("#TLE_file").val('');$("#TLE_file").click();}
else
data=$('#visualizationiframe')[0].contentWindow.DisplayREALTLEWW(a,b,c);}
function fileSelected(){var iMaxFilesize=1048576;var oFile=document.getElementById('TLE_file').files[0];systemname=oFile.name;var rFilter=/^(text\/plain)$/i;if(!rFilter.test(oFile.type)){console.log('Please choose text!');return;}
if(oFile.size>iMaxFilesize){console.log('Max Size exceed!');return;}
if(oFile){var r=new FileReader();r.onload=function(e){var contents=e.target.result;data=contents;rendertledataview();return data;}
r.readAsText(oFile);}else{console.log("Failed to load file");}}
function resetmodule(currentmodule){console.log('visualization.js','resetmodule','from',currentmodule);if(currentmodule=="visibility"){$('#visualizationiframe')[0].contentWindow.BigEarth.GSline.removeGS();$('#visualizationiframe')[0].contentWindow.SmallEarth.GSline.removeGS();$('#infopanel').css('display',"none");}
else if(currentmodule=="follow"||currentmodule.indexOf("Tracking")!=-1){$('#visualizationiframe')[0].contentWindow.stopButtonActionPerformed();$('#visualizationiframe')[0].contentWindow.document.getElementById('INFO').innerHTML="";$('#visualizationiframe')[0].contentWindow.followsatellite=!$('#visualizationiframe')[0].contentWindow.followsatellite;$('#visualizationiframe')[0].contentWindow.onesideview();}
else if(mode=="coverage24hr"||mode=="coverageww"||mode=="coverage"||currentmodule.indexOf("DOP")!=-1){$('#visualizationiframe')[0].contentWindow.removeLegend();$('#visualizationiframe')[0].contentWindow.heatmapdatapoints=[];if($('#visualizationiframe')[0].contentWindow.BigEarth.is2DMODE==false&&$('#visualizationiframe')[0].contentWindow.ecefeci=='ECI'){$('#visualizationiframe')[0].contentWindow.BigEarth.removefakeearth();$('#visualizationiframe')[0].contentWindow.BigEarth.createfakeearth();}
else{$('#visualizationiframe')[0].contentWindow.BigEarth.layers.remove($('#visualizationiframe')[0].contentWindow.BigEarth.heatmaplayer);if(!$('#visualizationiframe')[0].contentWindow.BigEarth.layers.contains($('#visualizationiframe')[0].contentWindow.BigEarth.earthlayer))
$('#visualizationiframe')[0].contentWindow.BigEarth.layers.add($('#visualizationiframe')[0].contentWindow.BigEarth.earthlayer,1);}
$('#visualizationiframe')[0].contentWindow.BigEarth.transparentGeoJson(false);}}
function showvisibility(method){if(mode&&mode!="visibility"){resetmodule(mode);}
if($('#visualizationiframe')[0].contentWindow.BigEarth.GSline.primitivesGS.length==0){if(mode=="visibility"){}
else{$('#visualizationiframe')[0].contentWindow.changelocation();setTimeout(function(){$('#infopanel').css('display','block');$('#hideinfopanel').click();},1000);}
$('#visualizationiframe')[0].contentWindow.BigEarth.GSline.removeGS();renderinfopanel($('#visualizationiframe')[0].contentWindow.BigEarth.calculateGSVisible(method));$('#visualizationiframe')[0].contentWindow.SmallEarth.GSline.removeGS();$('#visualizationiframe')[0].contentWindow.SmallEarth.calculateGSVisible(method);mode="visibility";}
else{resetmodule("visibility");mode=undefined;}}
function renderinfopanel(Visibledatas){$('#infocontent').html("");$('#infopanel').css('display',"block");for(var i=0;i<Visibledatas.length;i++){$('#infocontent').html($('#infocontent').html()+"<div id='polarcontainer"+Visibledatas[i].sel.label+"' style='width:100%;height:"+$('#infocontent').css('width')+";margin:0px;padding:2px;background:rgba(200,200,200,0.5);'></div>");$('#infocontent').html($('#infocontent').html()+"<div><table>"+visibletable(Visibledatas[i])+"</table></div><br><br>");processpolarmap('polarcontainer'+Visibledatas[i].sel.label,Visibledatas[i]);}
removestamp();function processpolarmap(name,Visibledata){var data=[];for(var i=0;i<Visibledata.value.length;i++){data.push({x:Visibledata.value[i].Azimuth,value:Visibledata.value[i].Elevation,satname:Visibledata.value[i].Name});}
var dataSet=anychart.data.set(data);var seriesData_1=dataSet;chart=anychart.polar();chart.container(name);chart.startAngle(0);chart.yScale().minimum(0).maximum(90);chart.yScale().ticks().interval(10);chart.yScale().inverted(true);chart.xScale().minimum(0).maximum(360);chart.xScale().ticks().interval(30);chart.xAxis().labels().textFormatter(function(){return this['value']+'°'});chart.title(false);chart.legend().align('center').enabled(true);var series1=chart.marker(seriesData_1);series1.name('Visible Satellite');series1.tooltip().titleFormatter(function(){return data[data.map(function(e){return e.x;}).indexOf(this.x)].satname;});series1.tooltip().textFormatter(function(){return"Elevation :　"+this.value+"\nAzimuth : "+this.x;});chart.draw();}
function visibletable(Visibledata){var value=Visibledata.value;var sel=Visibledata.sel;var tablecontent="";tablecontent+="<tr><td colspan='2'>TIME: "+$('#visualizationiframe')[0].contentWindow.currentJulianDate.getDateTimeStr()+"<br/>";tablecontent+="JulianDate: "+$('#visualizationiframe')[0].contentWindow.currentJulianDate.getJulianDate()+"<br/>";tablecontent+="Location: "+sel.label+"<br/>";tablecontent+="Latitude: "+sel.lat+"<br/>";tablecontent+="Longitude: "+sel.lon+"</td></tr>";tablecontent+="<tr><td colspan='2'><br>Visible Satellites</td></tr>";for(var j=0;j<value.length;j++){var pos=$('#visualizationiframe')[0].contentWindow.toLATLONTEXT($('#visualizationiframe')[0].contentWindow.toNormalLATLON(parseFloat(value[j].Position.x),parseFloat(value[j].Position.y),parseFloat(value[j].Position.z))).replace("(","").replace(")","");tablecontent+="<tr><td>"+(j+1)+".</td> <td>"+value[j].Name+" ["+parseFloat(pos.split(",")[0]).toFixed(2)+" ; "+parseFloat(pos.split(",")[1]).toFixed(2)+" ] <br>Elevation : "+(value[j].Elevation).toFixed(2)+"<br>Azimuth : "+(value[j].Azimuth).toFixed(2)+"</td></tr>";}
return tablecontent;}}
function showearthvisibility(DOP){if(mode&&DOP!=mode){resetmodule(mode);}
if($('#visualizationiframe')[0].contentWindow.heatmapdatapoints.length>0&&DOP==mode){resetmodule("DOP");mode=undefined;}
else{if($('#visualizationiframe')[0].contentWindow.BigEarth.is2DMODE==true||$('#visualizationiframe')[0].contentWindow.ecefeci=='ECEF')
$('#visualizationiframe')[0].contentWindow.BigEarth.transparentGeoJson(true);if(DOP!=mode){if($('#visualizationiframe')[0].contentWindow.BigEarth.is2DMODE==false&&$('#visualizationiframe')[0].contentWindow.ecefeci=='ECI')
$('#visualizationiframe')[0].contentWindow.BigEarth.fakeearth.whitelayer(true);else
$('#visualizationiframe')[0].contentWindow.BigEarth.layers.remove($('#visualizationiframe')[0].contentWindow.BigEarth.earthlayer,false);$('#visualizationiframe')[0].contentWindow.BigEarth.resetView();}
if(DOP=="coverage24hr"){showloading(true);$('#visualizationiframe')[0].contentWindow.stopButtonActionPerformed();$('#visualizationiframe')[0].contentWindow.BigEarth.calculate24hoursmedianearthVisibleWW();mode="coverage24hr";}
else if(DOP=="coverageww"){$('#visualizationiframe')[0].contentWindow.BigEarth.calculateearthVisibleWW();mode="coverageww";}
else if(DOP=="coverage"){$('#visualizationiframe')[0].contentWindow.BigEarth.calculateearthVisible();mode="coverage";}
else if(DOP){$('#visualizationiframe')[0].contentWindow.BigEarth.calculateearthDOP(DOP);mode=DOP;}}}
function follow(dim){console.log('visualization.js','follow');if(mode&&mode.indexOf("Tracking")==-1){resetmodule(mode);}
if(mode==undefined){$('#visualizationiframe')[0].contentWindow.followsatellite=!$('#visualizationiframe')[0].contentWindow.followsatellite;}else if(mode=="Tracking 3D"||mode=="Tracking 2D")
dim=null;if(dim=='2D'){$('#visualizationiframe')[0].contentWindow.follow2D3Dsatellite=true;mode="Tracking 2D";}
else if(dim==null){$('#visualizationiframe')[0].contentWindow.followsatellite=false;}
else{$('#visualizationiframe')[0].contentWindow.follow2D3Dsatellite=false;mode="Tracking 3D";}
if($('#visualizationiframe')[0].contentWindow.followsatellite==false){$('#visualizationiframe')[0].contentWindow.document.getElementById('INFO').innerHTML="";resetmodule("follow");mode=undefined;$('#visualizationiframe')[0].contentWindow.followsatellite=false;}
else{$('#visualizationiframe')[0].contentWindow.floatview();setTimeout(function(){if(($('#visualizationiframe')[0].contentWindow.BigEarth.is2DMODE==true&&mode=="Tracking 3D")||($('#visualizationiframe')[0].contentWindow.BigEarth.is2DMODE==false&&mode=="Tracking 2D")){$('#visualizationiframe')[0].contentWindow.SwitchViewMode();}
$('#visualizationiframe')[0].contentWindow.playButtonActionPerformed();},200);}}
function ecefeci(id){$('#visualizationiframe')[0].contentWindow.eciecef(id);}
function switchcolor(c){if(c.className=="viewmode"){$('.viewmode').css("color","#FFF");}
if(c.className=="systemselect"){$('.navp').css("display","block");$('.systemselect').css("color","#FFF");$('.navp').html("+");c.parentNode.getElementsByTagName("pre")[0].style.display="none";}
if(c.className=="ECIECEF"){$('.ECIECEF').css("color","#FFF");}
if(c.className=="ModuleCover"){if(c.style.color=="rgb(255, 255, 0)"){$('.ModuleCover').css("color","#FFF");return;}else{$('.ModuleCover').css("color","#FFF");}}
if(c.style.color=="rgb(255, 255, 0)"){c.style.color="#FFF";}
else{c.style.color="#FF0";if(c.className=="navp"){c.innerHTML=(c.innerHTML=="-"?"+":"-");c.style.color="#000";}}}
var videoframes=[];var recordinterval;var canrecord=true;function recordSS(){if(canrecord==false)return;if(videoframes.length==0){console.log("start recording");recordinterval=setInterval(function(){grabFrame(videoframes);},1000);$("#recordvideo").html('Video - <p style="color:#F00">STOP</p>');}else{$('#visualizationiframe')[0].contentWindow.stopAnimation();showloading(true);console.log("saving recorded frames : ",videoframes.length,"frames");canrecord=false;$("#recordvideo").html('Video - <p style="color:#FF0">Processing</p>');window.clearInterval(recordinterval);var canvas_html=$('#visualizationiframe')[0].contentWindow.BigEarth.viewer.canvas;gifshot.createGIF({'numWorkers':10,'gifWidth':canvas_html.width,'gifHeight':canvas_html.height,'images':videoframes,'numFrames':1,'interval':1},function(obj){if(!obj.error){if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)){var myBaseString=obj.image;var block=myBaseString.split(";");var dataType=block[0].split(":")[1];var realData=block[1].split(",")[1];var folderpath=cordova.file.externalRootDirectory;var filename="SATinfo.gif";console.log(folderpath,filename,realData,dataType);savebase64AsImageFile(folderpath,filename,realData,dataType);videoframes=[];$("#recordvideo").html('Video - Record');canrecord=true;}else{var a=document.createElement("a");a.download="SATinfo.gif";a.href=obj.image;a.click();hideloading();videoframes=[];$("#recordvideo").html('Video - Record');canrecord=true;alert("Successfully saved!");}}else{alert("Recorder Error!");}});}}
function downloadSS(){showloading(true);grabFrame();}
function grabFrame(framearray){var canvas_html=$('#visualizationiframe')[0].contentWindow.BigEarth.viewer.canvas;var newcanvas=document.createElement('canvas');newcanvas.id="newcanvas";newcanvas.width=canvas_html.width;newcanvas.height=canvas_html.height;var context=newcanvas.getContext('2d');var base_image=new Image();base_image.onload=function(){context.drawImage(this,0,0);DrawText(context,"SATinfo",10,25,"bold 15pt");var yoffset=30;DrawText(context,"Time : "+$('#visualizationiframe')[0].contentWindow.currentJulianDate.getDateTimeStr(),10,yoffset+=13);(systemname==""?"":DrawText(context,("System : "+systemname),10,yoffset+=13));DrawText(context,$('#visualizationiframe')[0].contentWindow.ecefeci.toUpperCase()+" Coordinate System",10,yoffset+=13);(appendsystemname==""?"":DrawText(context,(" + : "+appendsystemname),10,yoffset+=13));(mode==undefined?"":DrawText(context,("Mode : "+mode),10,yoffset+=13));var logoimage=new Image();logoimage.onload=function(){context.drawImage(this,context.canvas.width-155,context.canvas.height-52);if($('#visualizationiframe')[0].contentWindow.heatmaplegend!=null){var legendbarimage=new Image();legendbarimage.onload=function(){var legendwidth=context.canvas.width/3;context.drawImage(this,context.canvas.width/2-legendwidth/2,context.canvas.height-23*2,legendwidth,23);DrawText(context,$('#visualizationiframe')[0].contentWindow.document.getElementById("legend-val0").innerHTML,context.canvas.width/2-legendwidth/2,context.canvas.height-23/2,"10pt");DrawText(context,$('#visualizationiframe')[0].contentWindow.document.getElementById("legend-val1").innerHTML,context.canvas.width/2-legendwidth/2+legendwidth*0.117,context.canvas.height-23/2,"10pt");DrawText(context,$('#visualizationiframe')[0].contentWindow.document.getElementById("legend-val2").innerHTML,context.canvas.width/2-legendwidth/2+legendwidth*0.263,context.canvas.height-23/2,"10pt");DrawText(context,$('#visualizationiframe')[0].contentWindow.document.getElementById("legend-val3").innerHTML,context.canvas.width/2-legendwidth/2+legendwidth*0.644,context.canvas.height-23/2,"10pt");DrawText(context,$('#visualizationiframe')[0].contentWindow.document.getElementById("legend-val4").innerHTML,context.canvas.width/2-legendwidth/2+legendwidth*0.985,context.canvas.height-23/2,"10pt");downloadimage(framearray);};legendbarimage.src='images/legendbar.png';}else{downloadimage(framearray);}};logoimage.src='images/logo_new.png';}
base_image.src=canvas_html.toDataURL("image/png");function downloadimage(framearray){if(framearray){framearray.push(newcanvas.toDataURL("image/png"));return;}
if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)){var myBaseString=newcanvas.toDataURL("image/png");var block=myBaseString.split(";");var dataType=block[0].split(":")[1];var realData=block[1].split(",")[1];var folderpath=cordova.file.externalRootDirectory;var filename="SATinfo.png";console.log(folderpath,filename,realData,dataType);savebase64AsImageFile(folderpath,filename,realData,dataType);}else{var a=document.createElement("a");a.download="SATinfo.png";a.href=newcanvas.toDataURL("image/png");a.click();alert("Successfully saved!");}
hideloading();$("#newcanvas").remove();}
function DrawText(context,label,x,y,f){f=f||"6pt";context.save();context.textAlign="left";context.font=f+" Microsoft YaHei";context.lineWidth=0.5;context.strokeStyle='black';context.strokeText(label,x,y);context.font=f+" Microsoft YaHei";context.fillStyle='white';context.fillText(label,x,y);context.restore();}}
function b64toBlob(b64Data,contentType,sliceSize){contentType=contentType||'';sliceSize=sliceSize||512;var byteCharacters=atob(b64Data);var byteArrays=[];for(var offset=0;offset<byteCharacters.length;offset+=sliceSize){var slice=byteCharacters.slice(offset,offset+sliceSize);var byteNumbers=new Array(slice.length);for(var i=0;i<slice.length;i++){byteNumbers[i]=slice.charCodeAt(i);}
var byteArray=new Uint8Array(byteNumbers);byteArrays.push(byteArray);}
var blob=new Blob(byteArrays,{type:contentType});return blob;}
function savebase64AsImageFile(folderpath,filename,content,contentType){var DataBlob;if(contentType.indexOf("text/plain")!=-1){DataBlob=content;}
else{DataBlob=b64toBlob(content,contentType);}
console.log("Starting to write the file...");window.resolveLocalFileSystemURL(folderpath,function(dir){console.log("Access to the directory granted succesfully");dir.getFile(filename,{create:true},function(file){console.log("File created succesfully.");file.createWriter(function(fileWriter){fileWriter.write(DataBlob);fileWriter.onwriteend=function(){alert("Successfully saved! at "+folderpath);};fileWriter.onerror=function(e){alert("Unable to save file"+e.toString());};},function(){alert('Unable to save file in path '+folderpath);});});});}