function HeatMap(opts){this.config(opts);}
HeatMap.prototype={config:function(opts){var me=this;var w=opts.width,h=opts.height,id=opts.id;me.options={width:w,height:h,opacity:125,radius:2,bshadow:10,boundVal:15000,shadowBlur:1,points:{max:10,min:1,data:[]},gradient:{0.25:"rgb(0,0,255)",0.55:"rgb(0,255,0)",0.85:"yellow",1.0:"rgb(255,0,0)"}};var container=document.getElementById(id);var canvas=document.createElement("canvas"),ctx=canvas.getContext('2d');canvas.setAttribute("style","float:left;");canvas.width=w;canvas.height=h;container.appendChild(canvas);var pcanvas=document.createElement("canvas"),pctx=pcanvas.getContext('2d');pcanvas.width=1;pcanvas.height=256;pcanvas.style.display='none';container.appendChild(pcanvas);me.options.ctx=ctx;me.options.pctx=pctx;},renderShadow:function(x,y,val,cache){var me=this,ctx=me.options.ctx,radius=me.options.radius,bval=me.options.boundVal;var opacity=parseFloat(val/me.options.points.max,10);ctx.shadowColor=('rgba(0, 0, 0, '+opacity+')');ctx.shadowOffsetX=bval;ctx.shadowOffsetY=bval;ctx.shadowBlur=me.options.shadowBlur;ctx.beginPath();ctx.arc(x-bval,y-bval,me.options.radius,0,Math.PI*2,true);ctx.closePath();ctx.fill();if(!cache){me.cachePoint(x,y,val);}},colorize:function(){var me=this,w=me.options.width,h=me.options.height,ctx=me.options.ctx;var img=ctx.getImageData(0,0,w,h);var imgData=img.data,len=imgData.length,palette=me.getPalette();var opacity=me.options.opacity;for(var i=3;i<len;i+=4){var alpha=imgData[i],offset=alpha*4;if(!offset){continue;}
var finalAlpha=(alpha<opacity)?alpha:opacity;imgData[i-3]=palette[offset];imgData[i-2]=palette[offset+1];imgData[i-1]=palette[offset+2];imgData[i]=finalAlpha;}
img.data=imgData;ctx.putImageData(img,0,0);},getPalette:function(){var me=this,gradient=me.options.gradient,pctx=me.options.pctx;var grad=me.options.pctx.createLinearGradient(0,0,1,256);for(var x in gradient){grad.addColorStop(x,gradient[x]);}
pctx.fillStyle=grad;pctx.fillRect(0,0,1,256);return pctx.getImageData(0,0,1,256).data;},}
HeatMap.prototype.cachePoint=function(x,y,val){var me=this,points=me.options.points,data=points.data;if(val>points.max){points.max=val;}
data.push([x,y,val]);}
HeatMap.prototype.addPoint=function(x,y,val){var me=this;me.options.ctx.clearRect(0,0,me.options.width,me.options.height);me.options.pctx.clearRect(0,0,1,256);var data=me.options.points.data,len=data.length;for(var i=0;i<len;i++){me.renderShadow(data[i][0],data[i][1],data[i][2],true);}
me.renderShadow(x,y,val);me.colorize();}
HeatMap.prototype.randomPoints=function(points){var me=this;var w=me.options.width,h=me.options.height,max=200;for(var i=0;i<points;i++){me.renderShadow(Math.floor(Math.random()*w+1),Math.floor(Math.random()*h+1),Math.floor(Math.random()*max+1));}
me.colorize();}
HeatMap.prototype.removeallPoints=function(){var me=this;me.options.ctx.clearRect(0,0,me.options.width,me.options.height);me.options.pctx.clearRect(0,0,1,256);}
HeatMap.prototype.drawallPoints=function(array){var me=this;me.options.ctx.clearRect(0,0,me.options.width,me.options.height);me.options.pctx.clearRect(0,0,1,256);var data=array,len=data.length;for(var i=0;i<len;i++){me.renderShadow(data[i][0],data[i][1],data[i][2]);}
me.colorize();}