var SatelliteWorkers=[];var tledatalist=[];var mode=undefined;var realTimeAnimationRefreshRateMs=1000;var nonRealTimeAnimationRefreshRateMs=1000;var animationRefreshRateMs=realTimeAnimationRefreshRateMs;var animationSimStepSeconds=1.0;var currentPlayDirection=0;var timeStepSpeeds=new Array(0.0001,0.001,0.01,0.1,0.25,0.5,1.0,2.0,5.0,10.0,30.0,60.0,300.0,600.0,1800.0,3600.0,43200.0,86400.0,604800.0,2419200.0,31556926.0);var currentTimeStepSpeedIndex=6;var currentJulianDate=new Time();var followsatellite=false;var follow2D3Dsatellite=true;var followsatellitename=null;var followedsatellite=null;var ecefeci="ECEF";var orblinevis=true;var satlabvis=true;var satcovvis=false;var satvis=true;var visiblehashmap=new hashmap();var currentvisiblehashmap=new hashmap();var dophashmap=new hashmap();var heatmapdatapoints=[];var selectcustompoint=false;var prevSGP4Array=[];var VRMODE=(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent))?true:false;console.log("VR:",VRMODE);function EARTH(container,flat){this.container=container;this.selectedentity;this.is2DMODE=(flat?true:false);this.fakeearth;this.fakeearthrot=false;this.GSline;this.heatmaplayer;this.layers;this.satellite3d;this.SGP4Array=[];this.SatellliteNames=[];this.Collection=new Cesium.EntityCollection();this.playTimer;this.earthlayer;this.ArcgisLayer;this.currentlocation;this.gridlayer;this.maxheight=45000000;}
EARTH.prototype.initEARTH=function(){var transparentBaseLayer=new Cesium.SingleTileImageryProvider({url:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII="});this.viewer=new Cesium.Viewer(this.container,{selectionIndicator:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,infoBox:false,navigationHelpButton:false,navigationInstructionsInitiallyVisible:false,sceneMode:(this.is2DMODE?Cesium.SceneMode.SCENE2D:Cesium.SceneMode.SCENE3D),scene3DOnly:(this.is2DMODE?true:false),animation:false,timeline:false,fullscreenButton:false,skyBox:new Cesium.SkyBox({sources:{positiveX:'../Assets/stars/TychoSkymapII.t3_08192x04096_80_px.jpg',negativeX:'../Assets/stars/TychoSkymapII.t3_08192x04096_80_mx.jpg',positiveY:'../Assets/stars/TychoSkymapII.t3_08192x04096_80_py.jpg',negativeY:'../Assets/stars/TychoSkymapII.t3_08192x04096_80_my.jpg',positiveZ:'../Assets/stars/TychoSkymapII.t3_08192x04096_80_pz.jpg',negativeZ:'../Assets/stars/TychoSkymapII.t3_08192x04096_80_mz.jpg'}}),allowTextureFilterAnisotropic:false,contextOptions:{webgl:{alpha:false,preserveDrawingBuffer:true,failIfMajorPerformanceCaveat:false,depth:true,stencil:false,anialias:false},},targetFrameRate:60,resolutionScale:0.1,orderIndependentTranslucency:true,creditContainer:"hidecredit",imageryProvider:transparentBaseLayer,baseLayerPicker:false,geocoder:false,automaticallyTrackDataSourceClocks:false,dataSources:null,clock:null,vrButton:VRMODE,terrainShadows:Cesium.ShadowMode.DISABLED,});this.GSline=new orbitgsline(this.viewer);this.fakeearth=new fakeearth(this.viewer,currentJulianDate);this.scene=this.viewer.scene;this.scene.globe.show=true;this.scene.globe.enableLighting=false;this.scene.globe.showWaterEffect=false;this.scene.backgroundColor=Cesium.Color.TRANSPARENT;this.scene.globe.baseColor=Cesium.Color.TRANSPARENT;this.scene.canvas.style.backgroundColor='#21abcd';this.scene.sun=this.scene.sun&&this.scene.sun.destroy();this.scene.moon=this.scene.moon&&this.scene.moon.destroy();this.scene.sunBloom=false;this.scene.skyAtmosphere.brightnessShift=1.0;this.scene.fxaaOrderIndependentTranslucency=false;this.scene.debugShowFramesPerSecond=false;this.viewer.orderIndependentTranslucency=false;this.viewer.scene.fog.enabled=false;this.scene.imageryLayer=this.scene.imageryLayer&&this.scene.imageryLayer.destroy();if(!this.is2DMODE&&ecefeci=="ECI"){this.createfakeearth();}
this.layers=this.viewer.imageryLayers;this.layers.removeAll(true);var boundarieslayer=new Cesium.ImageryLayer(new Cesium.SingleTileImageryProvider({url:'../ResponsiveMobile/images/boundaries_trans.png',enablePickFeatures:false}));this.earthlayer=new Cesium.ImageryLayer(new Cesium.createTileMapServiceImageryProvider({url:'../Assets/imagery/NaturalEarthII/',maximumLevel:5}));this.layers.add(this.earthlayer);this.gridlayer=new Cesium.ImageryLayer(new Cesium.GridImageryProvider({cells:8,color:Cesium.Color(255,255,255,0.05),glowColor:Cesium.Color(1.0,1.0,1.0,0.05),minimumLevel:1,maximumLevel:5,glowWidth:1,canvasSize:1024,enablePickFeatures:false}));if(/Android|webOS|iPhone|iPod|iPad|BlackBerry/i.test(navigator.userAgent));else{this.layers.add(this.gridlayer);}
if(navigator.onLine==true||parent.connectionstate=="online"){try{var internet=false;$.ajax({url:"http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/1/0/1",type:'GET',crossDomain: true,async:false,success:function(){console.log("online mode");internet=true;},error:function(){console.log("offline mode");internet=false;}});if(internet==true){this.ArcgisLayer=new Cesium.ImageryLayer(new Cesium.ArcGisMapServerImageryProvider({url:'http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer',enablePickFeatures:false,minimumLevel:3,maximumLevel:5,alpha:0.0}));if(/Android|webOS|iPhone|iPod|iPad|BlackBerry/i.test(navigator.userAgent));else{this.layers.add(this.ArcgisLayer);}}}catch(e){}}
this.LoadGeoJson();this.resetView();updateTimeStepsDataGUI();disTime(currentJulianDate.getDateTimeStr());this.sethandler();}
EARTH.prototype.removeGeoJson=function(){this.viewer.dataSources.removeAll(true);this.viewer.dataSources=null;}
EARTH.prototype.LoadGeoJson=function(){console.log("LoadGeoJson:"+this.is2DMODE)
if(this.viewer.dataSources!=null)
this.removeGeoJson();var viewer=this.viewer;var flat=this.is2DMODE;var topojsonpath='../Assets/topojson/countriesSIMPLE.topojson';$.ajax({url:topojsonpath,type:'HEAD',success:function(){var datasource=new Cesium.GeoJsonDataSource();datasource.load(topojsonpath,{stroke:Cesium.Color.BLACK,strokeWidth:1,material:Cesium.Color.TRANSPARENT}).then(function(){if(flat){var geojsonentities=datasource.entities.values;for(var i=0;i<geojsonentities.length;i++){var entity=geojsonentities[i];entity.polygon.material=Cesium.Color.TRANSPARENT;}}});if(viewer.dataSources.get(0)==undefined)
viewer.dataSources.add(datasource);}});}
EARTH.prototype.transparentGeoJson=function(trans){console.log("transparentGeoJson:"+trans)
if(trans){if(this.viewer.dataSources.get(0)!=undefined){var geojsonentities=this.viewer.dataSources.get(0).entities.values;for(var i=0;i<geojsonentities.length;i++){var entity=geojsonentities[i];entity.polygon.material=Cesium.Color.TRANSPARENT;}}
if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent))
if(this.layers.contains(this.gridlayer))
this.layers.remove(this.gridlayer,false);}else{this.LoadGeoJson();if(!this.layers.contains(this.gridlayer))
this.layers.add(this.gridlayer);}}
function disSatelliteLocation(name,satposition){alert(name);document.getElementById('satellitetable').innerHTML="<tr><th>Satellite<th>Latitude<th>Longitude<th>Altitude<th>Velocity<th>Angle<th>Azimute<th>Elevation"
+"<tr><td>"+name+"<td>"+satposition.split(",")[0].substr(1,6)+"<td>"+satposition.split(",")[1].substr(0,6)+"<td>"+satposition.split(",")[2].split(")")[0]+"<td>0"+"<td>0"+"<td>0"+"<td>0";}
function disTime(TIME){document.getElementById("time_label").value=TIME;}
EARTH.prototype.resetSGP4state=function(){if(prevSGP4Array.length>0){for(var i=0;i<this.SGP4Array.length;i++){var index=-1;for(var j=0;j<prevSGP4Array.length;j++){if(prevSGP4Array[j].SGP4name==this.SGP4Array[i].SGP4name){index=j;break;}}
if(index!=-1){var show=this.SGP4Array[i].render=prevSGP4Array[index].render;console.log(index,show);this.SGP4Array[i].getSatellite().drawSatellite(show);this.SGP4Array[i].getSatellite().drawSatellitelab(show);this.SGP4Array[i].getOrbitline().drawline(orblinevis&&this.SGP4Array[i].render);if(this.is2DMODE==false)this.SGP4Array[i].getOrbitcone().drawCone(satcovvis&&this.SGP4Array[i].render);else this.SGP4Array[i].getOrbitcircle().drawCircle(satcovvis&&this.SGP4Array[i].render);}}}}
EARTH.prototype.resetView=function(){this.viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(0,0,(this.is2DMODE?40000000:this.maxheight)),duration:3});}
EARTH.prototype.gotoView=function(lat,lon){var newlon=(parseFloat(lon)+parseFloat((this.is2DMODE==false&&ecefeci=="ECI")?calculateearthrotation(currentJulianDate)-90:0));this.viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees((newlon>=180?newlon-360:newlon),lat,(this.is2DMODE?40000000:this.maxheight)),duration:3});}
EARTH.prototype.sethandler=function(){var viewer=this.viewer;var is2DMODE=this.is2DMODE;var selectedentity=this.selectedentity;var currentlocation=this.currentlocation;var handler=new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);handler.setInputAction(function(movement){this.resetView();},Cesium.ScreenSpaceEventType.RIGHT_CLICK);handler.setInputAction(function(movement){var pickedObjects=viewer.scene.pick(movement.endPosition);if(Cesium.defined(pickedObjects)){if(pickedObjects.id.name){selectedentity=pickedObjects.id;}}
if($("#CURRENTLOCATION").css("display")=="block"){var cartesian=viewer.camera.pickEllipsoid(movement.endPosition,viewer.scene.ellipsoid);if(cartesian){var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(cartesian);var rotation=Math.abs((is2DMODE==false&&ecefeci=="ECI")?(calculateearthrotation(currentJulianDate)-90):0);rotation=(rotation>180?rotation-360:rotation);var longitudeString=(Cesium.Math.toDegrees(wgs84.longitude)+rotation).toFixed(2);var latitudeString=Cesium.Math.toDegrees(wgs84.latitude).toFixed(2);currentlocation=latitudeString+","+longitudeString;if(currentlocation!="NaN,NaN"&&currentlocation!="114.59,0.00")
$("#CURRENTLOCATION div").html(""+currentlocation);}}},Cesium.ScreenSpaceEventType.MOUSE_MOVE);handler.setInputAction(function(movement){if(selectedentity){followsatellitename="___"+selectedentity.name;}
if(selectcustompoint==true){changecustomlocation(currentlocation.split(",")[0],currentlocation.split(",")[1],"Custom");displaycountrycontroller();$("#CURRENTLOCATION").css("display","none");selectcustompoint=false;console.log(selectcustompoint,currentlocation);}},Cesium.ScreenSpaceEventType.LEFT_CLICK);handler.setInputAction(function(movement){viewer.trackedEntity=undefined;},Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);}
EARTH.prototype.Switchto2Dmode=function(){this.is2DMODE=true;if(this.viewer.scene){this.removefakeearth();this.viewer.scene.morphTo2D(2);this.LoadGeoJson();}}
EARTH.prototype.Switchto3Dmode=function(){this.is2DMODE=false;if(this.scene){if(ecefeci=="ECI"){this.removeGeoJson();this.createfakeearth();}
this.scene.morphTo3D(2);}}
EARTH.prototype.SwitchViewMode=function(){if(this.is2DMODE==true){this.Switchto3Dmode();}
else{this.Switchto2Dmode();}
this.scene.globe.show=!this.is2DMODE;this.removeAll();if(parent.data!=null){processTLEstring(parent.data,true);}
this.scene.screenSpaceCameraController.enableRotate=!this.is2DMODE;this.scene.screenSpaceCameraController.enableTilt=!this.is2DMODE;setTimeout(function(){resetView();},4000);}
EARTH.prototype.createfakeearth=function(){this.fakeearth.createearth(currentJulianDate);}
EARTH.prototype.removefakeearth=function(){this.fakeearth.removeearth();}
EARTH.prototype.rotatefakeearth=function(){if(this.fakeearth){this.fakeearth.rotateearth(currentJulianDate);}}
EARTH.prototype.resetfakeearth=function(){if(this.fakeearth){this.fakeearth.resetearth();}}
EARTH.prototype.removeAll=function(){this.viewer.entities.removeAll();this.GSline.removeGS();for(var i=0;i<this.SGP4Array.length;i++){if(this.SGP4Array[i].getOrbitline())
this.SGP4Array[i].getOrbitline().drawline(false);}
if(this.is2DMODE||ecefeci=="ECEF"){this.removefakeearth();}
else{this.createfakeearth();}
if(this.SGP4Array.length!=0){prevSGP4Array=this.SGP4Array;}
this.SGP4Array=[];}
EARTH.prototype.resetModule=function(){this.GSline.removeGS();if(heatmapdatapoints.length>0){heatmapdatapoints=[];if(this.layers)
this.layers.remove(this.heatmaplayer);}
if(this.is2DMODE||ecefeci=="ECEF")
this.removefakeearth();}
function toXYZ(lng,lat,alt){var coord_wgs84=Cesium.Cartographic.fromDegrees(lng,lat,alt);var coord_xyz=Cesium.Ellipsoid.WGS84.cartographicToCartesian(coord_wgs84);return coord_xyz;}
function toNormalLATLON(x,y,z){var xyz=new Cesium.Cartesian3(x,y,z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);return Cesium.Cartesian3.fromDegrees(Cesium.Math.toDegrees(wgs84.longitude),Cesium.Math.toDegrees(wgs84.latitude),wgs84.height);}
function toLATLON(x,y,z){var xyz=new Cesium.Cartesian3(x,y,z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);return Cesium.Cartesian3.fromDegrees(Cesium.Math.toDegrees(wgs84.longitude),Cesium.Math.toDegrees(wgs84.latitude),wgs84.height);}
function toLATLONZERO(x,y,z){var xyz=new Cesium.Cartesian3(x,y,z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);return Cesium.Cartesian3.fromDegrees(Cesium.Math.toDegrees(wgs84.longitude),Cesium.Math.toDegrees(wgs84.latitude),wgs84.height);}
function toLATLONTEXT(position){var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(position);return"("+Cesium.Math.toDegrees(wgs84.longitude)+","+Cesium.Math.toDegrees(wgs84.latitude)+","+wgs84.height+")";}
EARTH.prototype.loopRendering=function(i){var sat=this.SGP4Array[i].getProp();var Satellite=this.SGP4Array[i].getSatellite();if(i==0&&this.is2DMODE==follow2D3Dsatellite&&followsatellite){if(followsatellitename==null||!followsatellitename)
followedsatellite=this.SGP4Array[0].getSatellite();else if((followsatellitename.indexOf("___"))!=-1){try{followedsatellite=this.SGP4Array[this.SatellliteNames.indexOf(followsatellitename.split("___")[1])].getSatellite();}catch(err){followedsatellite=this.SGP4Array[0].getSatellite();}}
this.viewer.flyTo(followedsatellite.satellite,{duration:0.3,offset:new Cesium.HeadingPitchRange(Cesium.Math.toRadians(0),Cesium.Math.toRadians(-90),10000000)});document.getElementById('INFO').innerHTML="Follow: "+followedsatellite.satellite.name+"<br> Position: "+toLATLONTEXT(followedsatellite.position);}
var oldLLA=sat.getLLA();currentJulianDate.addSeconds(0);var lla=sat.propogate2JulDate(getCurrentJulianDate());var p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,this.is2DMODE?16000:lla[2]);if((lla[0]>=0&&oldLLA[0]<=0&&oldLLA[0]<lla[0]&&orblinevis==true&&this.SGP4Array[i].render==true)){this.SGP4Array[i].drawOrbitline(sat.getName(),sat,getCurrentJulianDate(),orblinevis);}
if(i==0)
this.maxheight=lla[2];else
if(this.maxheight<lla[2])this.maxheight=lla[2];if(this.is2DMODE){if(this.SGP4Array[i].getOrbitcircle()){this.SGP4Array[i].getOrbitcircle().setPosition(p);this.SGP4Array[i].getOrbitcircle().drawCircle(satcovvis);}}
else if(this.is2DMODE==false){if(this.SGP4Array[i].getOrbitcone()){var xyz;if(ecefeci=="ECI"){xyz=sat.calculateTemePositionFromUT(getCurrentJulianDate());if(xyz!=null){p=toLATLON(xyz[0],xyz[1],xyz[2]);}}
else if(ecefeci=="ECEF"){p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,this.is2DMODE?16000:lla[2]);}
this.SGP4Array[i].getOrbitcone().setPosition(p);this.SGP4Array[i].getOrbitcone().drawCone(satcovvis);}}
Satellite.setSatelliteAttribute(p);Satellite.drawSatellitelab(satlabvis);}
EARTH.prototype.checkTimeDiffResetGroundTracks=function(timeDiffDays){if(timeDiffDays>91.0/1440.0){}}
EARTH.prototype.CalculateElevationAzimuth=function(SatellitePosition,GSlatlon,method){var degrad=180/Math.PI;var elevation=0;var azimuth=0;if(method){var GS=$V([GSlatlon.x,GSlatlon.y,GSlatlon.z]);var GSu=GS.devide(norm(GS));var SAT=$V([SatellitePosition.x,SatellitePosition.y,SatellitePosition.z]).subtract(GS);var SATu=SAT.devide(norm(SAT));elevation=(Math.PI/2-Math.acos(GSu.dot(SATu)))*degrad;satX=parseFloat(SatellitePosition.x);satY=parseFloat(SatellitePosition.y);satZ=parseFloat(SatellitePosition.z);obsX=parseFloat(GSlatlon.x);obsY=parseFloat(GSlatlon.y);obsZ=parseFloat(GSlatlon.z);azimuthcos=Math.acos(((-obsZ*obsX*(satX-obsX))-(obsZ*obsY*(satY-obsY))+((obsX*obsX+obsY*obsY)*(satZ-obsZ)))/Math.sqrt((obsX*obsX+obsY*obsY)*(obsX*obsX+obsY*obsY+obsZ*obsZ)*((satX-obsX)*(satX-obsX)+(satY-obsY)*(satY-obsY)+(satZ-obsZ)*(satZ-obsZ))));azimuthsin=Math.asin(((-obsY*(satX-obsX))+(obsX*(satY-obsY)))/Math.sqrt((obsX*obsX+obsY*obsY)*((satX-obsX)*(satX-obsX)+(satY-obsY)*(satY-obsY)+(satZ-obsZ)*(satZ-obsZ))));azimuth=azimuthsin*degrad+0;console.log(azimuth);}else{satX=parseFloat(SatellitePosition.x);satY=parseFloat(SatellitePosition.y);satZ=parseFloat(SatellitePosition.z);obsX=parseFloat(GSlatlon.x);obsY=parseFloat(GSlatlon.y);obsZ=parseFloat(GSlatlon.z);r=Math.sqrt((satX-obsX)*(satX-obsX)+(satY-obsY)*(satY-obsY)+(satZ-obsZ)*(satZ-obsZ));dx=(satX-obsX)/r;dy=(satY-obsY)/r;dz=(satZ-obsZ)/r;var xyz=new Cesium.Cartesian3(GSlatlon.x,GSlatlon.y,GSlatlon.z);var GSwgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);latOBS=GSwgs84.latitude;longOBS=GSwgs84.longitude;east=-Math.sin(longOBS)*dx+Math.cos(longOBS)*dy;north=-Math.cos(longOBS)*Math.sin(latOBS)*dx-Math.sin(longOBS)*Math.sin(latOBS)*dy+Math.cos(latOBS)*dz;vertical=Math.cos(longOBS)*Math.cos(latOBS)*dx+Math.sin(longOBS)*Math.cos(latOBS)*dy+Math.sin(latOBS)*dz;elevation=(Math.PI/2-Math.acos(vertical))*degrad;azimuth=Math.atan(east/north);var xyz=new Cesium.Cartesian3(SatellitePosition.x,SatellitePosition.y,SatellitePosition.z);var SATwgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);var dirlat=SATwgs84.latitude-GSwgs84.latitude;var dirlon=SATwgs84.longitude-GSwgs84.longitude;azimuth=Math.abs(azimuth);if(north>0&&east>0){azimuth=azimuth;}
else if(north>0&&east<0){azimuth=Math.PI*2-azimuth;}
else if(north<0&&east>0){azimuth=Math.PI-azimuth;}
else if(north<0&&east<0){azimuth=Math.PI+azimuth;}
azimuth=azimuth*degrad;}
return{elevation:elevation,azimuth:azimuth};}
EARTH.prototype.calculateGSVisible=function(method){var Visibilitydatas=[];for(var i=0;i<countries_stations.length;i++){if(countries_stations[i].isChecked==true){Visibilitydatas.push({value:this.calculateVisible(countries_stations[i].lat,countries_stations[i].lon,countries_stations[i].label,method),sel:countries_stations[i]});}}
return Visibilitydatas;}
EARTH.prototype.calculateVisible=function(lat,lon,name,method){var Visibilitydata=[];currentJulianDate.addSeconds(0);lat=parseFloat(lat);lon=parseFloat(lon);var juliandate=parseFloat(currentJulianDate.getJulianDate());var GSlatlon=this.ECEFlatlon(lat,lon,currentJulianDate);this.GSline.createGS(GSlatlon,name);for(var i=0;i<this.SGP4Array.length;i++){if(this.SGP4Array[i].render==false)continue;var Satellite=this.SGP4Array[i].getSatellite();var sat=this.SGP4Array[i].getProp();var lla=sat.propogate2JulDate(juliandate);var p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,lla[2]);if(this.is2DMODE==false&&ecefeci=="ECI"){var xyz=sat.calculateTemePositionFromUT(juliandate);if(xyz!=null){p=toLATLON(xyz[0],xyz[1],xyz[2]);}}
var SatellitePosition=p;const{elevation,azimuth}=this.CalculateElevationAzimuth(SatellitePosition,GSlatlon,method);if(15<=elevation&&elevation<=90){var Positions=[];Positions.push(GSlatlon);var xyz=new Cesium.Cartesian3(SatellitePosition.x,SatellitePosition.y,SatellitePosition.z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);var SatellitePosition;if(this.is2DMODE)
SatellitePosition=this.ECEFlatlon(Cesium.Math.toDegrees(wgs84.latitude),Cesium.Math.toDegrees(wgs84.longitude),currentJulianDate);else{if(ecefeci=="ECEF"){SatellitePosition=this.ECEFlatlon(Cesium.Math.toDegrees(wgs84.latitude),Cesium.Math.toDegrees(wgs84.longitude),currentJulianDate,wgs84.height);}}
Positions.push(SatellitePosition);this.GSline.createGSLine(Positions);var satname="";if(Satellite)satname=Satellite.name;Visibilitydata.push({Position:SatellitePosition,Name:satname,Elevation:elevation,Azimuth:azimuth});}
else;}
this.GSline.drawGSLine();return Visibilitydata;}
EARTH.prototype.calculateallVisible=function(lat,lon,time,range){visiblehashmap.clear();dophashmap.clear();var currenttime=new Time();if(time){currenttime.setTimeCalendar(time);}
currenttime.setHourtime(0);var step=range;var max=24*60*60;for(var r=0;r<=max;r=parseInt(r)+parseInt(step)){currenttime.setHourtime(0);currenttime.add("second",r);this.calculateperformanceVisiblility(lat,lon,currenttime);}}
EARTH.prototype.calculateperformanceVisiblility=function(lat,lon,timestr,addone){var currenttime=timestr;if(addone){currenttime=new Time();currenttime.setTime(timestr);currenttime.addSeconds(0);}
var juliandate=parseFloat(currenttime.getJulianDate());var GSlatlon=this.ECEFlatlon(lat,lon,currenttime);var GS=$V([GSlatlon.x,GSlatlon.y,GSlatlon.z]);var GSu=GS.devide(norm(GS));var H=$M([[0,0,0,0]]);var j=0;var Positions=[];for(var i=0;i<this.SGP4Array.length;i++){var sat=this.SGP4Array[i].getProp();var lla=sat.propogate2JulDate(juliandate);var p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,lla[2]);if(this.is2DMODE==false&&ecefeci=="ECI"){var xyz=sat.calculateTemePositionFromUT(juliandate);if(xyz!=null){p=toLATLON(xyz[0],xyz[1],xyz[2]);}
if(i==0){}}
var SatelliteName=this.SGP4Array[i].SGP4name;var SatellitePosition=p;const{elevation,azimuth}=this.CalculateElevationAzimuth(SatellitePosition,GSlatlon,method);if(15<=elevation&&elevation<=90){Positions.push({Position:SatellitePosition,Name:SatelliteName,Elevation:elevation,Azimuth:azimuth});var ENU=ECEF2ENU(SAT.elements[0],SAT.elements[1],SAT.elements[2],GSlatlon);var ENUv=$V([ENU[0],ENU[1],ENU[2]]);var ENUv=(ENUv.multiply(-1)).devide(norm(ENUv));H.elements[j++]=[ENUv.elements[0],ENUv.elements[1],ENUv.elements[2],1]}
else;}
visiblehashmap.put(currenttime.getDateTimeStr(),Positions);var G=((H.transpose()).multiply(H)).inv();var maxDOP=10;if(G!=null){var hdop=Math.sqrt(G.col(1).elements[0]+G.col(2).elements[1]);var vdop=Math.sqrt(G.col(3).elements[2]);var pdop=Math.sqrt(G.col(1).elements[0]+G.col(2).elements[1]+G.col(3).elements[2]);var tdop=Math.sqrt(G.col(4).elements[3]);var gdop=Math.sqrt((pdop*pdop)+(tdop*tdop));var DOPS=new hashmap();DOPS.put('hdop',checkvalue(hdop));DOPS.put('vdop',checkvalue(vdop));DOPS.put('pdop',checkvalue(pdop));DOPS.put('tdop',checkvalue(tdop));DOPS.put('gdop',checkvalue(gdop));dophashmap.put(currenttime.getDateTimeStr(),DOPS);function checkvalue(dop){var maxvalue=maxDOP;if(isNaN(dop)||dop>maxvalue){return maxvalue;}
return dop;}}else{var DOPS=new hashmap();DOPS.put('hdop',maxDOP);DOPS.put('vdop',maxDOP);DOPS.put('pdop',maxDOP);DOPS.put('tdop',maxDOP);DOPS.put('gdop',maxDOP);dophashmap.put(currenttime.getDateTimeStr(),DOPS);}}
EARTH.prototype.calculateearthVisible=function(){currentJulianDate.addSeconds(0);heatmapdatapoints=[];var juliandate=parseFloat(currentJulianDate.getJulianDate());for(var t=-90;t<=90;t+=10){var lat=t;var edgevalue=0;for(var n=180;n>=-180;n-=10){var lon=n;var GSlatlon=this.ECEFlatlon(lat,lon,currentJulianDate);var GS=$V([GSlatlon.x,GSlatlon.y,GSlatlon.z]);var GSu=GS.devide(norm(GS));var heatmappoints=[];heatmappoints.push((lon+180)/4);heatmappoints.push((90-lat)/4);var Positions=[];for(var i=0;i<this.SGP4Array.length;i++){if(this.SGP4Array[i].render==false)continue;var sat=this.SGP4Array[i].getProp();var lla=sat.propogate2JulDate(juliandate);var p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,lla[2]);if(this.is2DMODE==false&&ecefeci=="ECI"){var xyz=sat.calculateTemePositionFromUT(juliandate);if(xyz!=null){p=toLATLON(xyz[0],xyz[1],xyz[2]);}}
var SatelliteName=this.SGP4Array[i].SGP4name;var SatellitePosition=p;const{elevation,azimuth}=this.CalculateElevationAzimuth(SatellitePosition,GSlatlon);if(15<=elevation&&elevation<=90){if(this.is2DMODE||ecefeci=="ECEF"){var xyz=new Cesium.Cartesian3(SatellitePosition.x,SatellitePosition.y,SatellitePosition.z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);var SatellitePosition=this.ECEFlatlon(Cesium.Math.toDegrees(wgs84.latitude),Cesium.Math.toDegrees(wgs84.longitude),currentJulianDate);}
Positions.push({Position:SatellitePosition,Name:SatelliteName});}
else;}
heatmappoints.push(Positions.length);heatmapdatapoints.push(heatmappoints);heatmappoints=[];}}
var max=0;jQuery.map(heatmapdatapoints,function(obj){if(obj[2]>max)
max=obj[2];});heatmap.options.points.max=max;heatmap.drawallPoints(heatmapdatapoints);var layers=this.layers;if(this.is2DMODE||ecefeci=="ECEF"){if(this.layers){if(!this.layers.contains(this.heatmaplayer)){this.heatmaplayer=new Cesium.ImageryLayer(new Cesium.SingleTileImageryProvider({url:(document.getElementById("heatmapContainer").querySelector('canvas')).toDataURL({format:'jpeg',quality:0.1}),alpha:1.5,}));this.layers.add(this.heatmaplayer);}}}
else if(ecefeci=="ECI"){this.fakeearth.whitelayer(true);this.fakeearth.updateearth();}
initLegend();}
EARTH.prototype.calculateearthVisibleWW=function(){var prevsgp4title=[];var prevsgp4render=[];if(this.SGP4Array.length>0){for(var i=0;i<this.SGP4Array.length;i++){prevsgp4title.push(this.SGP4Array[i].SGP4name);prevsgp4render.push(this.SGP4Array[i].render);}}
SatelliteWorkers[0].postMessage({funct:'calculatecoverage',param:{time:currentJulianDate.getDateTimeStr(),prevsgp4title:prevsgp4title,prevsgp4render:prevsgp4render}});}
EARTH.prototype.calculateearthDOP=function(TYPE){currentJulianDate.addSeconds(0);heatmapdatapoints=[];var juliandate=parseFloat(currentJulianDate.getJulianDate());for(var t=-90;t<=90;t+=10){var lat=t;for(var n=180;n>=-180;n-=10){var lon=n;GsPosition=lat+"_"+lon;var GSlatlon=this.ECEFlatlon(lat,lon,currentJulianDate);var GS=$V([GSlatlon.x,GSlatlon.y,GSlatlon.z]);var GSu=GS.devide(norm(GS));var H=$M([[0,0,0,0]]);var j=0;var heatmappoints=[];heatmappoints.push((lon+180)/4);heatmappoints.push((90-lat)/4);var Positions=[];for(var i=0;i<this.SGP4Array.length;i++){if(this.SGP4Array[i].render==false)continue;var sat=this.SGP4Array[i].getProp();var lla=sat.propogate2JulDate(juliandate);var p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,lla[2]);if(this.is2DMODE==false&&ecefeci=="ECI"){var xyz=sat.calculateTemePositionFromUT(juliandate);if(xyz!=null){p=toLATLON(xyz[0],xyz[1],xyz[2]);}}
var SatelliteName=this.SGP4Array[i].SGP4name;var SatellitePosition=p;const{elevation,azimuth}=this.CalculateElevationAzimuth(SatellitePosition,GSlatlon);if(15<=elevation&&elevation<=90){var SAT=$V([SatellitePosition.x,SatellitePosition.y,SatellitePosition.z]).subtract(GS);var ENU=ECEF2ENU(SAT.elements[0],SAT.elements[1],SAT.elements[2],GSlatlon);var ENUv=$V([ENU[0],ENU[1],ENU[2]]);var ENUv=(ENUv.multiply(-1)).devide(norm(ENUv));H.elements[j++]=[ENUv.elements[0],ENUv.elements[1],ENUv.elements[2],1]}
else;}
var G=((H.transpose()).multiply(H)).inv();var DOP=10;if(G!=null){var hdop=Math.sqrt(G.col(1).elements[0]+G.col(2).elements[1]);var vdop=Math.sqrt(G.col(3).elements[2]);var pdop=Math.sqrt(G.col(1).elements[0]+G.col(2).elements[1]+G.col(3).elements[2]);var tdop=Math.sqrt(G.col(4).elements[3]);var gdop=Math.sqrt((pdop*pdop)+(tdop*tdop));switch(TYPE){case'PDOP':DOP=pdop;break;case'HDOP':DOP=hdop;break;case'VDOP':DOP=vdop;break;case'TDOP':DOP=tdop;break;case'GDOP':DOP=gdop;break;default:DOP=gdop;}}
if(DOP>10||DOP<0||isNaN(DOP)){DOP=10;}
heatmappoints.push(DOP);heatmapdatapoints.push(heatmappoints);heatmappoints=[];}}
var max=0;jQuery.map(heatmapdatapoints,function(obj){if(obj[2]>max)
max=obj[2];});heatmap.options.points.max=max;heatmap.drawallPoints(heatmapdatapoints);var layers=this.layers;if(this.is2DMODE||ecefeci=="ECEF"){if(this.layers){if(!this.layers.contains(this.heatmaplayer)){this.heatmaplayer=new Cesium.ImageryLayer(new Cesium.SingleTileImageryProvider({url:(document.getElementById("heatmapContainer").querySelector('canvas')).toDataURL({format:'jpeg',quality:0.1}),alpha:1.5,}));layers.add(this.heatmaplayer);}}}
else if(ecefeci=="ECI"){this.fakeearth.whitelayer(true);this.fakeearth.updateearth();}
initLegend();}
EARTH.prototype.calculate24hoursmedianearthVisibleWW=function(){var prevsgp4title=[];var prevsgp4render=[];if(this.SGP4Array.length>0){for(var i=0;i<this.SGP4Array.length;i++){prevsgp4title=this.SGP4Array[i].SGP4name;prevsgp4render=this.SGP4Array[i].render;}}
SatelliteWorkers[0].postMessage({funct:'calculate24hr',param:{prevsgp4title:prevsgp4title,prevsgp4render:prevsgp4render}});}
EARTH.prototype.calculate24hoursmedianearthVisible=function(){stopAnimation();currentJulianDate.addSeconds(0);heatmapdatapoints=[];var juliandate=parseFloat(currentJulianDate.getJulianDate());var GsPosition;for(var t=-90;t<=90;t+=10){var lat=t;for(var n=180;n>=-180;n-=10){var lon=n;GsPosition=lat+"_"+lon;var GSlatlon=this.ECEFlatlon(lat,lon,currentJulianDate);var GS=$V([GSlatlon.x,GSlatlon.y,GSlatlon.z]);var GSu=GS.devide(norm(GS));var H=$M([[0,0,0,0]]);var j=0;var heatmappoints=[];heatmappoints.push((lon+180)/4);heatmappoints.push((90-lat)/4);var median=0;for(var hour=0;hour<24;hour++){var currenttime=new Time();currenttime.setHourtime(hour);var juliandate=parseFloat(currenttime.getJulianDate());var Positions=0;for(var i=0;i<this.SGP4Array.length;i++){if(this.SGP4Array[i].render==false)continue;var sat=this.SGP4Array[i].getProp();var lla=sat.propogate2JulDate(juliandate);var p=Cesium.Cartesian3.fromDegrees(lla[1]*180.0/Math.PI,lla[0]*180.0/Math.PI,lla[2]);if(this.is2DMODE==false&&ecefeci=="ECI"){var xyz=sat.calculateTemePositionFromUT(juliandate);if(xyz!=null){p=toLATLON(xyz[0],xyz[1],xyz[2]);}}
var SatelliteName=this.SGP4Array[i].SGP4name;var SatellitePosition=p;const{elevation,azimuth}=this.CalculateElevationAzimuth(SatellitePosition,GSlatlon);if(15<=elevation&&elevation<=90){if(this.is2DMODE||ecefeci=="ECEF"){var xyz=new Cesium.Cartesian3(SatellitePosition.x,SatellitePosition.y,SatellitePosition.z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);var SatellitePosition=this.ECEFlatlon(Cesium.Math.toDegrees(wgs84.latitude),Cesium.Math.toDegrees(wgs84.longitude),currentJulianDate);}
Positions++;}
else;}
median+=Positions;}
median=median/24;heatmappoints.push(median);heatmapdatapoints.push(heatmappoints);heatmappoints=[];}}
var max=0;jQuery.map(heatmapdatapoints,function(obj){if(obj[2]>max)
max=obj[2];});heatmap.options.points.max=max;heatmap.drawallPoints(heatmapdatapoints);var layers=this.layers;if(this.is2DMODE||ecefeci=="ECEF"){if(!this.layers.contains(this.heatmaplayer)){this.heatmaplayer=new Cesium.ImageryLayer(new Cesium.SingleTileImageryProvider({url:(document.getElementById("heatmapContainer").querySelector('canvas')).toDataURL("image/png"),alpha:1.5}));layers.add(this.heatmaplayer);}}
else if(ecefeci=="ECI")
this.fakeearth.updateearth();initLegend();}
EARTH.prototype.calculateallVisibleWW=function(lat,lon){visiblehashmap.clear();var dataarray=[];alert("started!",SatelliteWorkers.length);for(var i=0;i<24;i++){for(var j=0;j<tledatalist.length;j++){if(SatelliteWorkers.length<tledatalist.length){const worker=new Worker("js/worker/sgp4_worker.js");worker.postMessage({funct:'init',param:tledatalist[j]});worker.onmessage=receiveFromWorker;SatelliteWorkers.push(worker);console.log("new webworker",SatelliteWorkers.length);}
SatelliteWorkers[j].postMessage({funct:'propagate',param:i});}}
function receiveFromWorker(e){const{result,time}=e.data;dataarray.push(result);if(dataarray.length==tledatalist.length){const worker=new Worker("js/worker/visible_worker_intime.js");worker.postMessage({sgp4arrays:dataarray});worker.onmessage=VisibilityResult;dataarray=[];}
function VisibilityResult(e){visiblehashmap.put(time,e.data);console.log(time,e.data);}}}
EARTH.prototype.ECEFlatlon=function(lat,lon,juldate,height){var newlon=(lon+((this.is2DMODE==false&&ecefeci=="ECI")?calculateearthrotation(juldate)-90:0));return Cesium.Cartesian3.fromDegrees(newlon>=180?newlon-360:newlon,lat,height?height:0);}
function ECEF2ENU(x,y,z,GSlatlon){var u=x-GSlatlon.x;var v=y-GSlatlon.y;var w=z-GSlatlon.z;var xyz=new Cesium.Cartesian3(GSlatlon.x,GSlatlon.y,GSlatlon.z);var wgs84=Cesium.Ellipsoid.WGS84.cartesianToCartographic(xyz);var lat=Cesium.Math.toRadians(wgs84.latitude);var lon=Cesium.Math.toRadians(wgs84.longitude);var t=Math.cos(lon)*u+Math.sin(lon)*v;var E=-Math.sin(lon)*u+Math.cos(lon)*v;var N=-Math.sin(lat)*t+Math.cos(lat)*w;var U=Math.cos(lat)*t+Math.sin(lat)*w;return[E,N,U];}
function norm(vector){var V=vector.elements||vector;return Math.sqrt((V[0]*V[0])+(V[1]*V[1])+(V[2]*V[2]));}