importScripts("../TLErenderer/Time.js")
importScripts("../TLErenderer/SatelliteTleSGP4.js")
importScripts("../TLErenderer/SGP4unit.js")
importScripts("../TLErenderer/Kepler.js")
importScripts("../TLErenderer/GeoFunctions.js")
importScripts("../TLErenderer/MathUtils.js")
importScripts("../TLErenderer/J2kCoordinateConversion.js")
importScripts("../TLErenderer/AstroConst.js")
importScripts("../TLErenderer/Time.js")
importScripts("../TLErenderer/TLE.js")
importScripts("../TLErenderer/SGP4.js")
importScripts("../TLErenderer/SGP4utils.js")
importScripts("../TLErenderer/SGP4SatData.js")
importScripts("../TLErenderer/SatelliteTleSGP4.js")
importScripts("../MatricesnVector/sylvester.js")
var result;var prop;self.onmessage=e=>{const{funct,param}=e.data;switch(funct){case"init":prop=calculateSGP4(param.name,param.line1,param.line2);break;case"propagate":var currenttime=new Time();currenttime.setHourtime(param);var juliandate=parseFloat(currenttime.getJulianDate());result=prop.propogate2JulDate(juliandate);self.postMessage({result:result,time:currenttime.getDateTimeStr()});break;}};