function fakeearth(viewer,currentJulianDate){this.viewer=viewer;this.fakeearthlon=calculateearthrotation(currentJulianDate);this.primitivefakeearth=[];this.Primearth=[];this.earthrad=AstroConst.R_Earth;this.heatmapProperty=null;}
fakeearth.prototype.createearth=function(currentJulianDate){this.viewer.scene.globe.show=false;if(this.primitivefakeearth.length==0){var pos;if(currentJulianDate){pos=Cesium.Cartesian3.fromDegrees(calculateearthrotation(currentJulianDate),-90,-this.earthrad);}
else{pos=Cesium.Cartesian3.fromDegrees(0,-90,-this.earthrad);}
this.Primearth.push(new Cesium.GeometryInstance({geometry:new Cesium.EllipsoidGeometry({vertexFormat:Cesium.PerInstanceColorAppearance.POSITION_ONLY,position:pos,radii:new Cesium.Cartesian3(this.earthrad,this.earthrad,this.earthrad)}),outline:true}));var objeto=new Cesium.Primitive({geometryInstances:this.Primearth,appearance:new Cesium.EllipsoidSurfaceAppearance({material:new Cesium.Material({fabric:{type:'Color',uniforms:{color:Cesium.Color.TRANSPARENT,transparent:true}}}),flat:true,aboveGround:true}),allowPicking:false});objeto.modelMatrix=Cesium.Transforms.eastNorthUpToFixedFrame(pos);this.primitivefakeearth.push(objeto);this.viewer.scene.primitives.add(this.primitivefakeearth[this.primitivefakeearth.length-1]);this.Primearth=[];if(heatmapdatapoints.length>0){this.heatmapProperty=(document.getElementById("heatmapContainer").querySelector('canvas')).toDataURL({format:'jpeg',quality:0.1})}
this.Primearth.push(new Cesium.GeometryInstance({geometry:new Cesium.EllipsoidGeometry({vertexFormat:Cesium.PerInstanceColorAppearance.POSITION_ONLY,position:pos,radii:new Cesium.Cartesian3(this.earthrad+2000,this.earthrad+2000,this.earthrad+2000),})}));var objeto2=new Cesium.Primitive({geometryInstances:this.Primearth,appearance:new Cesium.EllipsoidSurfaceAppearance({material:new Cesium.Material({fabric:{type:'Image',uniforms:{image:'images/NaturalEarth2_small.png'}}})}),allowPicking:false});objeto2.modelMatrix=Cesium.Transforms.eastNorthUpToFixedFrame(pos);this.primitivefakeearth.push(objeto2);this.viewer.scene.primitives.add(this.primitivefakeearth[this.primitivefakeearth.length-1]);this.Primearth=[];}}
fakeearth.prototype.updateearth=function(){var appr=new Cesium.MaterialAppearance({material:new Cesium.Material({fabric:{type:'Image',uniforms:{image:(document.getElementById("heatmapContainer").querySelector('canvas')).toDataURL({format:'jpeg',quality:0.1}),alpha:1.5},components:{diffuse:'texture2D(image, materialInput.st).rgb',alpha:'texture2D(image, materialInput.st).a * alpha'}}}),faceForward:true,translucent:true,flat:true});this.primitivefakeearth[this.primitivefakeearth.length-2].appearance=appr;}
fakeearth.prototype.removeearth=function(){this.viewer.scene.globe.show=true;if(this.primitivefakeearth.length>0){for(var i=0;i<this.primitivefakeearth.length;i++)
this.viewer.scene.primitives.remove(this.primitivefakeearth[i]);this.Primlines=[];this.primitivefakeearth=[];console.log("removeearth");}}
fakeearth.prototype.rotateearth=function(currentJulianDate){if(this.primitivefakeearth.length>0){var pos=Cesium.Cartesian3.fromDegrees(calculateearthrotation(currentJulianDate),-90,-this.earthrad);for(var i=0;i<this.primitivefakeearth.length;i++)
this.primitivefakeearth[i].modelMatrix=Cesium.Transforms.eastNorthUpToFixedFrame(pos);}}
fakeearth.prototype.resetearth=function(){var pos=Cesium.Cartesian3.fromDegrees(0,-90,-this.earthrad);for(var i=0;i<this.primitivefakeearth.length;i++)
this.primitivefakeearth[i].modelMatrix=Cesium.Transforms.eastNorthUpToFixedFrame(pos);}
var prevwhite=false;fakeearth.prototype.whitelayer=function(white){if(prevwhite!=white){this.primitivefakeearth[this.primitivefakeearth.length-1].appearance.material=new Cesium.Material({fabric:{type:'Image',uniforms:{image:white?'images/BlankMap-Equirectangular.svg':'images/NaturalEarth2.png',transparent:true}}});prevwhite=white;}}
function calculateearthrotation(juliandate){var currentMJD=juliandate.getMJD();var offsetRotdeg=0;var T=(currentMJD-51544.5)/36525.0;var rotateECIdeg=((280.46061837+360.98564736629*(currentMJD-51544.5))+0.000387933*T*T-T*T*T/38710000.0+offsetRotdeg)%360.0;return rotateECIdeg;}